// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One connected account (a WhatsApp login). mautrix models each login as a
 * Matrix Space whose children are that account's chats, so an account IS a Space.
 */
export type Account = { 
/**
 * The backing Space room id: the stable key used to filter the inbox.
 */
id: string, 
/**
 * Human label: the Space's display name (the bridge sets this per account).
 */
label: string, };
