// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One aggregated reaction on a message: the emoji, who reacted (display
 * names), and whether the signed-in user is among them. `senders.len()` is
 * the count; `reacted_by_me` drives the own-highlight + toggle-off UI.
 */
export type ReactionGroup = { key: string, senders: Array<string>, reacted_by_me: boolean, };
