// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quoted context for a rich reply: who + what the message replies to. When
 * the replied-to event's details aren't loaded yet, `sender_name` is empty
 * and `body` is a placeholder — the UI renders a generic quote block.
 */
export type ReplyPreview = { sender_name: string, body: string, };
