// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The result of trying to restore a saved session on launch.
 *
 * WHY A TYPE INSTEAD OF `Option<String>`
 * Restore can end three ways, and the login screen must tell them apart:
 *   - there was no saved session at all → show a plain login form,
 *   - a session existed but the server rejected it (revoked/expired token) →
 *     show "Session expired, please log in again",
 *   - it worked → skip login and go straight to the inbox.
 * The old `Option<String>` collapsed the first two into `None`, so the UI could
 * never show the "expired" message. `status` names the outcome; `user_id` is set
 * only for `restored`.
 */
export type RestoreOutcome = { 
/**
 * One of: "restored" | "none" | "expired".
 */
status: string, 
/**
 * The Matrix user id, present only when `status == "restored"`.
 */
user_id: string | null, };
