// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A minimal, serializable view of a room for the UI.
 *
 * `#[derive(TS)]` + `#[ts(export)]` makes `ts-rs` generate a matching
 * TypeScript type, so the Rust <-> TS boundary can never silently drift — the
 * gotcha we flagged when choosing this stack. The generated file lands in
 * `../src/bindings/` and the frontend imports it. Regenerate via `cargo test`.
 */
export type RoomSummary = { id: string, name: string | null, unread: bigint, 
/**
 * Whether this room is a bridged chat. Placeholder for now; a real
 * implementation inspects room state for the bridge's marker events.
 */
is_bridged: boolean, 
/**
 * Our membership: "joined" | "invited" | "left" | "knocked" | "banned".
 * The mautrix bridge invites us into each WhatsApp portal and waits for us
 * to accept, so many real chats start "invited" — the UI dims those + offers
 * Accept instead of opening into a 403. Derived from room.state().
 */
membership: string, 
/**
 * Preview of the most recent text message, if any.
 */
last_message: string | null, 
/**
 * Timestamp (ms since epoch) of that latest message — drives recency sort
 * and a relative "2m / 3h / Mon" label in the inbox. f64 → plain TS number.
 */
last_ts: number | null, 
/**
 * The account (WhatsApp login) this chat belongs to, as the backing bridge
 * Space's room id. None for rooms not inside any account Space (e.g. the
 * bridge management room). The UI maps the id to a label via list_accounts.
 */
account: string | null, 
/**
 * m.favourite tag — pinned chats sort first in the inbox.
 */
pinned: boolean, 
/**
 * m.lowpriority tag — archived chats are hidden behind the Archived filter.
 */
archived: boolean, 
/**
 * Per-room push rule set to Mute.
 */
muted: boolean, };
