// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One hit from server-side full-text message search (across ALL chats).
 */
export type SearchHit = { room_id: string, room_name: string | null, sender_name: string, body: string, ts: number, };
